### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sucrecacao** [Peltoche/vixi#22]
I git-cloned the repo and ran : `cargo install --path .`
and got the following error:
(xi was not pre-installed
```
error[E0658]: use of unstable library feature 'mem_take'
   --> /home/joe/.cargo/git/checkouts/xi-editor-e3bc3cb50a6bb63b/4f93edb/rust/rope/src/breaks.rs:228:24
    |
228 |             let leaf = mem::take(&mut self.leaf);
    |                        ^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/61129

error[E0658]: use of unstable library feature 'mem_take'
   --> /home/joe/.cargo/git/checkouts/xi-editor-e3bc3cb50a6bb63b/4f93edb/rust/rope/src/spans.rs:130:28
    |
130 |             let mut leaf = mem::take(&mut self.leaf);
    |                            ^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/61129

   Compiling toml v0.5.6
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `xi-rope`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `vixi v0.1.0 (/home/joe/src/vixi)`, intermediate artifacts can be found at `/home/joe/src/vixi/target`

Caused by:
  build failed
``
Ubuntu 19.04 
rustc 1.37.0

**Comment by ImmemorConsultrixContrarie** [comment]
`mem::take` function was stabilized in 1.40, but you are trying to compile with 1.37 rustc.

**Comment by jakbyte** [comment]
try `rustup update`

**Comment by wackbyte** [comment]
i'm guessing the rust package on ubuntu is outdated, so you should try installing rustup to get the latest rust version

**Comment by sucrecacao** [comment]
Yes upgrading to rustc 1.40 fixed the issue.
